const menu = [
  {
    id: 1,
    category: "Coffee Drinks",

    sub_category: "hot coffee drink",
    name: "Dark Chocolate Mocha",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "hot1",
    short_description:
      "This is chocolate and coffee-lover's favorite! a great combination of espresso, chocolate and steamed milk foam",
  },

  {
    id: 2,
    category: "Coffee Drinks",

    sub_category: "hot coffee drink",
    name: "Cappuccino",
    price_sm: 2,
    price_md: 3,
    price_lg: 4,
    img_url: "hot2",
    short_description:
      "The Italian coffee drink that is traditionally prepared with equal parts double espresso, steamed milk and steamed cream foam on top. Espresso is typically made with a dark roasted coffee from Italy and ground finely",
  },
  {
    id: 3,
    category: "Coffee Drinks",
    sub_category: "hot coffee drink",
    name: "Flat White",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "hot3",
    short_description:
      "An espresso-based drink with thin layer of steamed milk.",
  },
  {
    id: 4,
    category: "Coffee Drinks",
    sub_category: "hot coffee drink",
    name: "Latte",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "hot4",
    short_description:
      "Espresso-based coffee traditionally prepared with little more layer of steamed milk foam than Flat White coffee",
  },
  {
    id: 5,
    category: "Coffee Drinks",
    sub_category: "hot coffee drink",
    name: "Green Tea Latte",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "hot5",
    short_description:
      "Espresso-based coffee combine in the right amount of green tea and top with steamed milk foam",
  },
  {
    id: 6,
    category: "Coffee Drinks",
    sub_category: "hot coffee drink",
    name: "Mexican Coffee",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "hot6",
    short_description:
      "Indulge in this flavorful drink from our neighbors to the south that pairs robust coffee with chocolate, spice, citrus and vanilla. It's magic in a cup!",
  },
  {
    id: 7,
    category: "Coffee Drinks",
    sub_category: "hot coffee drink",
    name: "Hot Mocha Float",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "hot7",
    short_description:
      "Indulgent espresso based, cocoa, chocolate blended together for a creamy indulgence.",
  },
  {
    id: 8,
    category: "Coffee Drinks",
    sub_category: "hot coffee drink",
    name: "Cafe au Lait",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "hot8",
    short_description:
      "Cafe au Lait(coffee with milk) consists of equal parts coffee and steamed milk and top with cream foam",
  },
  {
    id: 9,
    category: "Coffee Drinks",
    sub_category: "cold coffee drink",
    name: "Cappuccino on Ice",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "cold1",
    short_description:
      "Combination of strong espresso and sweetened condensed milk, half-and-half, a little sugar and vanilla",
  },
  {
    id: 10,
    category: "Coffee Drinks",
    sub_category: "cold coffee drink",
    name: "Iced Caramel Macchiato",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "cold2",
    short_description:
      "A perfect balance of espresso, vanilla, milk and caramel.",
  },
  {
    id: 11,
    category: "Coffee Drinks",
    sub_category: "cold coffee drink",
    name: "Vietnamese Iced Coffee",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "cold3",
    short_description:
      "Espresso over ice with sweetened condensed milk is an unbeatable Southeast Asian treat",
  },
  {
    id: 12,
    category: "Coffee Drinks",
    sub_category: "cold coffee drink",
    name: "Chocolate Iced Mocha",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "cold4",
    short_description:
      "Espresso-based coffee perfectly blend with cocoa, almond milk on the ice",
  },
  {
    id: 13,
    category: "Coffee Drinks",
    sub_category: "cold coffee drink",
    name: "Vanilla Iced Coffee",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "cold5",
    short_description:
      "Homemade vanilla simple syrup gives a fragrant hint of sweetness to your iced Espresso coffee.",
  },
  {
    id: 14,
    category: "Coffee Drinks",
    sub_category: "cold coffee drink",
    name: "Coconut Caramel Cold Brew",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "cold6",
    short_description:
      "The toasted flavor of caramel pairs beautifully with coconut and cold brew espresso",
  },
  {
    id: 15,
    category: "Coffee Drinks",
    sub_category: "cold coffee drink",
    name: "Toasted Coconut Shakerato",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "cold7",
    short_description:
      "Italian iced coffee, made by shaking coffee with ice and toasted coconut syrup, top with creamy coconut milk",
  },
  {
    id: 16,
    category: "Coffee Drinks",
    sub_category: "cold coffee drink",
    name: "Overnight New Orleans-Style Iced Coffee",
    price_sm: 3.5,
    price_md: 5.5,
    price_lg: 7,
    img_url: "cold8",
    short_description:
      "Espresso-based coffee infuse it with cinnamon and chicory (a New Orleans classic) overnight.",
  },
  {
    id: 17,
    category: "breakfast",
    name: "buttermilk pancakes",
    price: 15.99,
    img_url: "",
    short_description: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 18,
    category: "breakfast",
    name: "country delight",
    price: 20.99,
    img_url: "",
    short_description: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 19,
    category: "shakes",
    name: "godzilla milkshake",
    price: 6.99,
    img_url: "",
    short_description: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 20,
    category: "shakes",
    name: "quarantine buddy",
    price: 16.99,
    img_url: "",
    short_description: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];

export default menu;
